import { MenuItem, CategoryInfo } from './types';

export const HERO_IMAGE = '/src/assets/images/user_real_storefront_final_1781856959733.jpg';

export const MENU_ITEMS: MenuItem[] = [
  // ===============================================
  // 🐐 SIGNATURE GOAT SPECIALTIES ('signature-goat')
  // ===============================================
  {
    id: 'tere-siga',
    name: 'Tere Siga',
    nameAm: 'በረዶ የደረቀ ጥሬ ሥጋ',
    nameOm: 'Foon Re\'ee Dheedhi Tere Siga',
    description: 'Fresh premium raw goat meat served with authentic wild highland mitmita and thick awaze paste.',
    descriptionAm: 'ለየት ባለ ጥንቃቄ የተመረጠ ምርጥ የፍየል ጥሬ ሥጋ ከሚጥሚጣ እና ከአዋዜ ጋር የሚቀርብ::',
    descriptionOm: 'Foon re\'ee dheedhii filatamaa mitmita fi awaaze wajjin dhiyaatu.',
    price: 550,
    category: 'signature-goat',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
    isPopular: true,
    isChefChoice: true,
    isSpicy: true,
    isGlutenFree: true,
    isAvailable: true
  },
  {
    id: 'kurt-siga',
    name: 'Kurt Siga',
    nameAm: 'ቁርጥ ሥጋ',
    nameOm: 'Foon Muraa Kurt Siga',
    description: 'Fresh hand-cubed organic goat meat prepared with traditional Ethiopian spices and rich clarified mustard oil.',
    descriptionAm: 'በየቀኑ ትኩስ የታረደ የፍየል ቁርጥ ሥጋ ከባህላዊ ቅመማ ቅመሞች ጋር የሚቀርብ::',
    descriptionOm: 'Foon re\'ee muramee qophaaye mi\'eessitoota aadaa wajjin.',
    price: 520,
    category: 'signature-goat',
    image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=600&auto=format&fit=crop&q=80',
    isPopular: true,
    isChefChoice: false,
    isSpicy: true,
    isGlutenFree: true,
    isAvailable: true
  },
  {
    id: 'leb-leb',
    name: 'Leb Leb Siga',
    nameAm: 'ለብ ለብ ፍየል ሥጋ',
    nameOm: 'Leb Leb Foon Re\'ee',
    description: 'Lightly seared pan-fired premium tender goat meat chunks sizzling with hot onions and jalapenos.',
    descriptionAm: 'በትንሹ በእሳት ላይ የሞቀ የፍየል ሥጋ ከሽንኩርት እና ከቃሪያ ጋር በሞቃት የሸክላ ሳህን ላይ የሚቀርብ::',
    descriptionOm: 'Foon re\'ee xiqqoo ibidda irra caqasame qorqodamee qophaaye.',
    price: 480,
    category: 'signature-goat',
    image: 'https://images.unsplash.com/photo-1514516345957-556ca7d90a29?w=600&auto=format&fit=crop&q=80',
    isPopular: false,
    isChefChoice: true,
    isSpicy: true,
    isGlutenFree: true,
    isAvailable: true
  },
  {
    id: 'feyel-tibs',
    name: 'Traditional Feyel Tibs',
    nameAm: 'ባህላዊ የፍየል ጥብስ',
    nameOm: 'Feyel Tibs Aadaa',
    description: 'Traditional Ethiopian goat meat sautéed with sweet highland onions, rosemary, and authentic spices.',
    descriptionAm: 'የተመረጠ የፍየል ስጋ ከቀይ ሽንኩርት፣ ባህላዊ ቅመሞች እና ከሮዝመሪ ጋር ተጠብሶ በከሰል ድንጋይ የሚቀርብ::',
    descriptionOm: 'Feyel tibs beera aadaa, shunkurti fi dhandhama gaarii wajjin kan dhiyaatu.',
    price: 350,
    category: 'signature-goat',
    image: '/src/assets/images/feyel_tibs_1781852326700.jpg',
    isPopular: true,
    isChefChoice: true,
    isSpicy: true,
    isGlutenFree: true,
    isAvailable: true
  },
  {
    id: 'special-house-tibs',
    name: 'Special House Tibs',
    nameAm: 'ልዩ የታልተለ በረንዳ ጥብስ',
    nameOm: 'Special House Tibs Taltele',
    description: 'Premium selected goat fillet sautéed with organic garlic butter (Niter Kibbeh), bell peppers, and cardamon.',
    descriptionAm: 'ለየት ያለ ጥንቃቄ ከተደረገለት የክትፎ ስጋ ጋር የሚመጣጠን የፍየል ስጋ ጥብስ በንጥር ቅቤ እና በቃሪያ የተዘጋጀ::',
    descriptionOm: 'Foon re\'ee qullaa\'aa sirriitti dhiyaatu dhadhaa niter kibbeh fi qulqullina addaa wajjin.',
    price: 460,
    category: 'signature-goat',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
    isPopular: true,
    isChefChoice: true,
    isSpicy: false,
    isGlutenFree: true,
    isAvailable: true
  },
  {
    id: 'dulet-goat',
    name: 'Goat Dulet',
    nameAm: 'የፍየል ዱለት',
    nameOm: 'Dulet Feyel',
    description: 'Finely minced premium goat tripe, liver, and lean red meat pan-seared with Niter Kibbeh, ginger, cardamom, and hot Mitmita.',
    descriptionAm: 'በትንሹ የተከተፈ የፍየል ስጋ፣ ጨጓራ እና ጉበት በንጥር ቅቤ እና በሚጥሚጣ ተቆልቶ የሚቀርብ ባህላዊ ምግብ::',
    descriptionOm: 'Foon re\'ee, tiruu sirriitti qoramee qophaaye dhadhaa fi mitmitaa wajjin.',
    price: 340,
    category: 'signature-goat',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&auto=format&fit=crop&q=80',
    isPopular: false,
    isChefChoice: true,
    isSpicy: true,
    isGlutenFree: true,
    isAvailable: true
  },
  {
    id: 'kikil',
    name: 'Goat Kikil (Spiced Stew)',
    nameAm: 'የፍየል ቅቅል',
    nameOm: 'Kikil Feyel',
    description: 'Slow-cooked bone-in succulent goat meat soup enriched with cardamon, wild garlic, jalapeno pods, and potatoes.',
    descriptionAm: 'ለሰዓታት በጸጥታ የበሰለ የፍየል የጎድን ስጋ ቅቅል ከሽንኩርት፣ ድንች እና ከቃሪያ ጋር የሚቀርብ ልዩ ፈሳሽ የምግብ አይነት::',
    descriptionOm: 'Foon re\'ee lafee wajjin affeelame qophaayu qullubbii fi jinjibila wajjin.',
    price: 380,
    category: 'signature-goat',
    image: '/src/assets/images/goat_soup_1781852357576.jpg',
    isPopular: true,
    isChefChoice: false,
    isSpicy: false,
    isGlutenFree: true,
    isAvailable: true
  },
  {
    id: 'dinich-be-siga',
    name: 'Dinich Be Siga',
    nameAm: 'ድንች በሥጋ',
    nameOm: 'Dinich Be Siga (Dinnicha Foon)',
    description: 'Nourishing slow-simmered potato and premium goat meat stew cooked in a mild red pepper and turmeric sauce.',
    descriptionAm: 'ከትኩስ ድንች እና ከፍየል ስጋ የተዘጋጀ ድንቅ መረቅ በደማቅ አልጫ መልክ የሚቀርብ::',
    descriptionOm: 'Afelaa dinnichaa fi foon re\'ee sirriitti bilcheeffame.',
    price: 290,
    category: 'signature-goat',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&auto=format&fit=crop&q=80',
    isPopular: false,
    isChefChoice: false,
    isSpicy: false,
    isGlutenFree: true,
    isAvailable: true
  },
  {
    id: 'key-wat-siga',
    name: 'Key Wat Siga',
    nameAm: 'የፍየል ቀይ ወጥ',
    nameOm: 'Key Wat Foon Re\'ee',
    description: 'Classic rich and hot spicy goat meat stew, slowly cooked with premium Ethiopian Berbere and purified butter.',
    descriptionAm: 'በባህላዊ መንገድ በበርበሬ እና በንጥር ቅቤ ለረጅም ሰአት የበሰለ ድንቅ የፍየል ቀይ ወጥ::',
    descriptionOm: 'Kookii foon re\'ee kan berbere qabu dhadhaa aadaa sirriitti qophaaye.',
    price: 360,
    category: 'signature-goat',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80',
    isPopular: false,
    isChefChoice: false,
    isSpicy: true,
    isGlutenFree: true,
    isAvailable: true
  },
  {
    id: 'mixed-goat-platter',
    name: 'Taltale Mega Mixed Goat Platter',
    nameAm: 'ልዩ የፍየል ድግስ በያይነቱ',
    nameOm: 'Mixed Goat Platter (Ma\'ed Feyel)',
    description: 'An ultimate imperial sharing display: combining Tere Siga, sizzling Tibs, fresh Dulet, and warm Kikil soup over fresh teff injera.',
    descriptionAm: 'የፍየል ጥብስ፣ ዱለት፣ ጥሬ ስጋ እና ቅቅል መረቅ በአንድ ላይ በትልቅ ሞሰብ ላይ ተሰናድቶ የሚቀርብ የታልተለ ልዩ ድግስ::',
    descriptionOm: 'Makuu foon re\'ee hundaa: foon dheedhii, tibs, dulet fi marak affeelame tokkoon dhiyaatu.',
    price: 1350,
    category: 'signature-goat',
    image: '/src/assets/images/family_feast_1781852341486.jpg',
    isPopular: true,
    isChefChoice: true,
    isSpicy: true,
    isGlutenFree: true,
    isAvailable: true
  },

  // ===============================================
  // ETHIOPIAN TRADITIONAL FOODS ('traditional-foods')
  // ===============================================
  {
    id: 'kitfo',
    name: 'Classic Kitfo',
    nameAm: 'ባህላዊ ክትፎ',
    nameOm: 'Kitfo Aadaa',
    description: 'Finely minced extra-lean beef seasoned with hot Mitmita chili and spiced butter. Served with homemade cheese (Ayib) and collard greens (Gomen).',
    descriptionAm: 'ለስላሳ ስጋ በቅቤ እና በሚጥሚጣ ተለውሶ ከአይብ እና ከጎመን ጋር የሚቀርብ ተወዳጅ የኢትዮጵያ ወግ::',
    descriptionOm: 'Kitfo lafee malee sirriitti qoramee dhadhaa fi mitmitaa wajjin kessummeeffamu layib fi gomen wajjin.',
    price: 380,
    category: 'traditional-foods',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80',
    isPopular: true,
    isChefChoice: true,
    isSpicy: true,
    isGlutenFree: true,
    isAvailable: true
  },
  {
    id: 'gored-gored',
    name: 'Gored Gored',
    nameAm: 'ጎረድ ጎረድ',
    nameOm: 'Gored Gored Beef',
    description: 'Juicy large cubes of raw premium beef warm-dipped in spiced butter, Berbere, and Awaze mustard cream.',
    descriptionAm: 'በትላልቅ ቅርፅ የተከተፈ ጥሬ የበሬ ስጋ በንጥር ቅቤ እና አዋዜ ተለውሶ የሚቀርብ የምግብ አይነት::',
    descriptionOm: 'Siga dheedhii kuubii dhedheeraa berbere fi dhadhaa wajjin.',
    price: 390,
    category: 'traditional-foods',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&auto=format&fit=crop&q=80',
    isPopular: false,
    isChefChoice: false,
    isSpicy: true,
    isGlutenFree: true,
    isAvailable: true
  },
  {
    id: 'doro-wat',
    name: 'Festive Doro Wat',
    nameAm: 'የአውደ ዓመት ዶሮ ወጥ',
    nameOm: 'Doro Wat Aadaa',
    description: 'Rich slow-stewed chicken legs and hardboiled eggs in caramelized onions and deep Berbere sauce with Niter Kibbeh.',
    descriptionAm: 'ለብዙ ሰአታት በሽንኩርት እና በበርበሬ የበሰለ እውነተኛ የሀገር ዶሮ ወጥ፤ ከቀይ እቁላል ጋር የሚቀርብ የድግስ ንጉሥ::',
    descriptionOm: 'Kooki kofoo lukkuu fi buphaa affeelame berbere addaa wajjin.',
    price: 450,
    category: 'traditional-foods',
    image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=600&auto=format&fit=crop&q=80',
    isPopular: true,
    isChefChoice: true,
    isSpicy: true,
    isGlutenFree: true,
    isAvailable: true
  },
  {
    id: 'shiro-tegabino',
    name: 'Shiro Tegabino',
    nameAm: 'ሽሮ ተጋቢኖ',
    nameOm: 'Shiro Tegabino',
    description: 'Slow-cooked spiced chickpea flour sauce simmered in a roaring clay pot with garlic and green chilies.',
    descriptionAm: 'በሸክላ ሳህን ላይ ፈልቶ የሚቀርብ ምርጥ ሽሮ በሽንኩርት፣ ነጭ ሽንኩርት እና በንጥር ቅቤ ወይም በዘይት የተዘጋጀ::',
    descriptionOm: 'Shiro afelaa qorqodamee dhiyaatu clay pot keessatti.',
    price: 210,
    category: 'traditional-foods',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&auto=format&fit=crop&q=80',
    isPopular: false,
    isChefChoice: false,
    isSpicy: true,
    isGlutenFree: true,
    isVegan: true,
    isAvailable: true
  },
  {
    id: 'tibs-firfir',
    name: 'Tibs Firfir',
    nameAm: 'የስጋ ጥብስ ፍርፍር',
    nameOm: 'Tibs Firfir',
    description: 'Shredded sourdough injera rolls soaked in deep spicy berbere reduction gravy tossed with pan-fried goat meat.',
    descriptionAm: 'በትኩስ የፍየል ስጋ የተዘጋጀ ጥብስ እንጀራ ከበርበሬ መረቅ ጋር ፍርፍር ተደርጎ የሚቀርብ ጣፋጭ ምግብ::',
    descriptionOm: 'Buddeena muramee dhibbaa foon re\'ee sirriitti bilcheeffame wajjin.',
    price: 310,
    category: 'traditional-foods',
    image: 'https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?w=600&auto=format&fit=crop&q=80',
    isPopular: true,
    isChefChoice: false,
    isSpicy: true,
    isGlutenFree: true,
    isAvailable: true
  },
  {
    id: 'beyaynetu-combo',
    name: 'Yetsom Beyaynetu Planner',
    nameAm: 'የጾም በያይነቱ ድግስ',
    nameOm: 'Yetsom Beyaynetu Combo',
    description: 'An elegant presentation of split lentils, yellow peas, collard greens, beetroot, and cabbage stews on teff injera.',
    descriptionAm: 'መልካም መልክ ያላቸው የጾም ምግቦች፤ ምስር ወጥ፣ ክክ፣ አትክልት እና ሰላጣ በአንድ ላይ በጤፍ እንጀራ ላይ የሚቀርብ::',
    descriptionOm: 'Beyaynetu soomaa midhaan garaa garaa buddeena xaafii wajjin.',
    price: 320,
    category: 'traditional-foods',
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600&auto=format&fit=crop&q=80',
    isPopular: true,
    isChefChoice: false,
    isSpicy: false,
    isGlutenFree: true,
    isVegan: true,
    isAvailable: true
  },

  // ===============================================
  // BREAKFAST MENU ('breakfast')
  // ===============================================
  {
    id: 'chechebsa',
    name: 'Golden Chechebsa (Kitta Firfir)',
    nameAm: 'ጣፋጭ ጨጨብሳ',
    nameOm: 'Qancara (Chechebsa)',
    description: 'Shredded house-baked wheat flatbread sautéed with hot Berbere essence, organic honey, and spiced ghee.',
    descriptionAm: 'ከላመ የስንዴ ቂጣ ተዘጋጅቶ በበርበሬ እና በንጥር ቅቤ ወይም ማር የተለወሰ የጠዋት ኃይል ሰጪ ምግብ::',
    descriptionOm: 'Kittaa kookii xiqqoo muramee dhadhaa fi damma wajjin kan dhiyaatu.',
    price: 190,
    category: 'breakfast',
    image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=600&auto=format&fit=crop&q=80',
    isPopular: true,
    isChefChoice: true,
    isSpicy: false,
    isGlutenFree: false,
    isAvailable: true
  },
  {
    id: 'kinche',
    name: 'Highland Kinche',
    nameAm: 'ኪንጬ',
    nameOm: 'Kinche Aadaa',
    description: 'Cracked wheat kernels slow-boiled to fluffy perfection, tossed with gold clarified spiced butter or olive oil.',
    descriptionAm: 'ከተሰነጠቀ ስንዴ በጥንቃቄ የተቀቀለ ኪንጬ በቅቤ አውታር ተለውሶ የሚቀርብ ቀላል መቆያ::',
    descriptionOm: 'Oatmeal dhandhama gaarii qabu dhadhaa ykn zayita zeitiiniin qophaaye.',
    price: 150,
    category: 'breakfast',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&auto=format&fit=crop&q=80',
    isPopular: false,
    isChefChoice: false,
    isSpicy: false,
    isGlutenFree: false,
    isAvailable: true
  },
  {
    id: 'foul',
    name: 'Special Fava Foul',
    nameAm: 'ልዩ ስፔሻል ፉል',
    nameOm: 'Foul Speshall',
    description: 'Warm fava bean mash seasoned with cumin, cardamon, chopped red onions, tomatoes, green chilies, hardboiled egg, and feta cheese.',
    descriptionAm: 'ከትኩስ ባቄላ የተፈጨ ፉል በቲማቲም፣ ሽንኩርት፣ ቃሪያ፣ ዘይት እና አይብ ወይም እቁላል ተሰናድቶ የሚቀርብ::',
    descriptionOm: 'Fava bean qorqodamee qophaayu tomato, shunkurti fi buphaa wajjin.',
    price: 180,
    category: 'breakfast',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&auto=format&fit=crop&q=80',
    isPopular: true,
    isChefChoice: false,
    isSpicy: false,
    isGlutenFree: false,
    isAvailable: true
  },
  {
    id: 'fatira',
    name: 'Crispy Fatira with Honey',
    nameAm: 'ፋቲራ ከማር ጋር',
    nameOm: 'Fatira Damma Wajjin',
    description: 'Layers of crispy thin golden pastry pancake served scrambled with eggs, accompanied by warm wild forest honey.',
    descriptionAm: 'ቀጭን የቃሪያ ፋቲራ ከእንቁላል ጋር ተጠብሶ ከጫካ የተገኘ ንጹህ ማር ጋር የሚቀርብ የጠዋት ምግብ::',
    descriptionOm: 'Pan-cake crispy damma fi buphaa wajjin dhiyaatu.',
    price: 170,
    category: 'breakfast',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&auto=format&fit=crop&q=80',
    isPopular: false,
    isChefChoice: false,
    isAvailable: true
  },
  {
    id: 'enkulal-firfir',
    name: 'Special Enkulal Firfir',
    nameAm: 'እንቁላል ፍርፍር',
    nameOm: 'Enkulal Firfir',
    description: 'Three organic eggs scrambled with chopped plum tomatoes, red parameters onions, spicy green chilies, served with freshly baked bread rolls.',
    descriptionAm: 'ሶስት እንቁላል ከቲማቲም፣ ሽንኩርት እና ክትፎ ቃሪያ ጋር ተጠብሶ ከሙቅ ዳቦ ጋር የሚቀርብ ፈጣን ቁርስ::',
    descriptionOm: 'Egg scrambled timatima, shunkurti fi qorqoda bilcheefame.',
    price: 160,
    category: 'breakfast',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80',
    isPopular: true,
    isAvailable: true
  },
  {
    id: 'bula',
    name: 'Traditional Bula (Enset porridge)',
    nameAm: 'ባህላዊ የቡላ ገንፎ',
    nameOm: 'Garfo Bula Aadaa',
    description: 'Nourishing thick porridge made from dried organic Enset plant powder, with a deep crater filled with spiced butter and honey.',
    descriptionAm: 'ከቆጮ ተክል የተገኘ ምርጥ ቡላ ገንፎ መሃሉ ላይ በንጥር ቅቤ እና በሚጥሚጣ ተሞልቶ የሚቀርብ ባህላዊ ቁርስ::',
    descriptionOm: 'Bula porridge dhadhaa fi mitmitaa wajjin.',
    price: 220,
    category: 'breakfast',
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600&auto=format&fit=crop&q=80',
    isPopular: false,
    isChefChoice: true,
    isAvailable: true
  },

  // ===============================================
  // SOUPS & STARTERS ('soups-starters')
  // ===============================================
  {
    id: 'goat-soup',
    name: 'Ye-Feyel Marak (Goat Soup)',
    nameAm: 'የፍየል መረቅ / ሾርባ',
    nameOm: 'Ye-Feyel Marak (Soup re\'ee)',
    description: 'Highly concentrated slow-simmered highland goat bone marrow broth rich with garlic, wild ginger, herbs, and cardamom.',
    descriptionAm: 'ለረጅም ሰአት የተቀቀለ የታማኝ የፍየል የጎድንና የእግር አጥንት መረቅ በቅመማቅመም የተዘጋጀ::',
    descriptionOm: 'Lafee re\'ee affeelame qullubbii fi jinjibila wajjin kan dhiyaatu marak gaariidha.',
    price: 180,
    category: 'soups-starters',
    image: '/src/assets/images/goat_soup_1781852357576.jpg',
    isPopular: true,
    isChefChoice: true,
    isGlutenFree: true,
    isAvailable: true
  },
  {
    id: 'bone-broth-soup',
    name: 'Rich Bone Broth Soup',
    nameAm: 'ደማቅ የአጥንት መቅኒ ሾርባ',
    nameOm: 'Marrow Bone Broth',
    description: 'Pure slow-cooked highland goat bone marrow stock sprinkled with mountain herbs, shallots, and fresh black pepper.',
    descriptionAm: 'የተመረጠ የአጥንት መቅኒ ሾርባ በሀገር ባህል ቅመሞች የተዘጋጀ ፈሳሽ ጥንካሬ ሰጪ መረቅ::',
    descriptionOm: 'Lafee makuu marak foon re\'ee dhandhama gaarii wajjin.',
    price: 200,
    category: 'soups-starters',
    image: 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?w=600&auto=format&fit=crop&q=80',
    isPopular: false,
    isChefChoice: false,
    isGlutenFree: true,
    isAvailable: true
  },
  {
    id: 'house-special-soup',
    name: 'House Special Veg Soup',
    nameAm: 'የታሪካዊው ታልተለ አትክልት ሾርባ',
    nameOm: 'Soup Special Veg',
    description: 'Creamy vegetable purée simmered with split green peas, garden herbs, carrots, and sweet leeks.',
    descriptionAm: 'ከተለያዩ የአትክልት አይነቶችና ሮዝመሪ የተዘጋጀ ቀላልና ጣፋጭ የሾርባ አይነት::',
    descriptionOm: 'Atsilte garaa garaa qorqodamee bilcheeffame.',
    price: 160,
    category: 'soups-starters',
    image: 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?w=600&auto=format&fit=crop&q=80',
    isPopular: false,
    isVegan: true,
    isGlutenFree: true,
    isAvailable: true
  },
  {
    id: 'fresh-salad',
    name: 'Timatim Salata (Tomato Salad)',
    nameAm: 'ትኩስ የቲማቲም ሰላጣ',
    nameOm: 'Timatim Salata Red',
    description: 'Chopped ripe organic tomatoes, crisp purple onions, and jalapenos tossed in lemon juice and premium olive oil.',
    descriptionAm: 'ቲማቲም፣ ሽንኩርት እና ቃሪያ በሎሚ ጭማቂና በወይራ ዘይት የተዘጋጀ ባህላዊ ሰላጣ::',
    descriptionOm: 'Tomato muramee shunkurti fi qorqoda lemunaaan qophaaye.',
    price: 130,
    category: 'soups-starters',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&auto=format&fit=crop&q=80',
    isPopular: false,
    isVegan: true,
    isGlutenFree: true,
    isAvailable: true
  },

  // ===============================================
  // HOT DRINKS ('hot-drinks')
  // ===============================================
  {
    id: 'coffee-ceremony',
    name: 'Traditional Buna Ceremony',
    nameAm: 'ዕጣን የጨሰበት ባህላዊ ጄበና ቡና',
    nameOm: 'Sirna Buna Aadaa',
    description: 'Freshly clay-roasted Sidama beans hand-ground and brewed in a clay Jebena. Served with complimentary salted popcorn and incense.',
    descriptionAm: 'በደንበኞቻችን ፊት የሚቆላና በሸክላ ጄበና የሚፈላ መዓዛው የሚስብ ምርጥ ቡና፤ ከፋንዲሻና ከዕጣን ጋር የሚቀርብ::',
    descriptionOm: 'Sirna buna jebenan qophaaye popcorn bilisaa wajjin.',
    price: 75,
    category: 'hot-drinks',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80',
    isPopular: true,
    isChefChoice: true,
    isAvailable: true
  },
  {
    id: 'macchiato',
    name: 'Creamy Macchiato',
    nameAm: 'ማኪያቶ',
    nameOm: 'Macchiato Espresso',
    description: 'Double-shot premium highland espresso crowned with thick velvety steamed milk foam, sweet Ethiopian style.',
    descriptionAm: 'ከትኩስ ወተትና ጥቁር ቡና በጥበብ የተሰናዳ ማኪያቶ በደንበኛው ፍላጎት የሚዘጋጅ::',
    descriptionOm: 'Espresso milk foam sirriitti kessummeeffame.',
    price: 70,
    category: 'hot-drinks',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80',
    isPopular: false,
    isAvailable: true
  },
  {
    id: 'espresso',
    name: 'Highland Espresso',
    nameAm: 'ኤስፕሬሶ',
    nameOm: 'Espresso Buna',
    description: 'Dark concentrated highland single-origin Arabica espresso with a thick golden crema layer.',
    descriptionAm: 'ጽኑና ንፁህ የቡና ፍሬ ማውጫ ኤስፕሬሶ ሀይል ሰጪ ድንቅ መጠጥ::',
    descriptionOm: 'Espresso gurraacha dhandhama addaa qabu.',
    price: 60,
    category: 'hot-drinks',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80',
    isPopular: false,
    isAvailable: true
  },
  {
    id: 'cappuccino',
    name: 'Foamy Cappuccino',
    nameAm: 'ካፑቺኖ',
    nameOm: 'Cappuccino Foamy',
    description: 'Rich espresso blended with silky hot texturized milk and finished with a dusting of organic cocoa.',
    descriptionAm: 'ጣፋጭ ካፑቺኖ በቸኮሌት ዱቄት የተጌጠ የጠዋት መነቂያ::',
    descriptionOm: 'Buna cappuccino dhadhaa wajjin.',
    price: 80,
    category: 'hot-drinks',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80',
    isPopular: false,
    isAvailable: true
  },
  {
    id: 'spiced-tea',
    name: 'Traditional Spiced Shai',
    nameAm: 'የቅመም ሻይ',
    nameOm: 'Shai Spiced Aadaa',
    description: 'Premium organic black tea leaves steeped with whole cardamom pods, cloves, cinnamon, and fresh ginger.',
    descriptionAm: 'ቀረፋ፣ ቅርንፉድ፣ ኮረሪማና ጅንጅብል የፈላበት እውነተኛ የማዕዘ ሻይ መጠጥ::',
    descriptionOm: 'Shai qarafaa fi jinjibila wajjin qophaayu dhandhama kookii.',
    price: 45,
    category: 'hot-drinks',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&auto=format&fit=crop&q=80',
    isPopular: false,
    isAvailable: true
  },

  // ===============================================
  // COLD DRINKS ('cold-drinks')
  // ===============================================
  {
    id: 'soft-drinks',
    name: 'Carbonated Sodas & Ambo Mineral',
    nameAm: 'ለስላሳ መጠጦች እና አምቦ ውሃ',
    nameOm: 'Sodas & Ambo Water',
    description: 'Chilled selection of favorite sodas or glass bottle natural thermal spring carbonated Ambo mineral water.',
    descriptionAm: 'ቀዝቃዛ ለስላሳ መጠጦች ወይም ተፈጥሮአዊው የአምቦ ጠርሙስ ማዕድን ውሃ::',
    descriptionOm: 'Qabbaneessaa sodas ykn bishaan ambo qopheeffame.',
    price: 50,
    category: 'cold-drinks',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&auto=format&fit=crop&q=80',
    isPopular: false,
    isAvailable: true
  },
  {
    id: 'fresh-juices',
    name: 'Fresh Mango & Avocado Juice',
    nameAm: 'ትኩስ ማንጎ እና አቮካዶ ጁስ',
    nameOm: 'Juice Mango & Avocado',
    description: 'Thick layered fresh pulpy mango, avocado, and papaya smoothie served chilled with fresh lime squeeze.',
    descriptionAm: 'ትኩስ ማንጎ እና አቮካዶ በአስደናቂ ሁኔታ ተደራርቦ የሚቀርብ የተፈጥሮ ፍራፍሬ ጭማቂ፤ ከሎሚ ጋር::',
    descriptionOm: 'Juice makuu mango fi avocado qabbanaawaa lemuna wajjin.',
    price: 110,
    category: 'cold-drinks',
    image: 'https://images.unsplash.com/photo-1536882240095-0379873feb4e?w=600&auto=format&fit=crop&q=80',
    isPopular: true,
    isChefChoice: true,
    isAvailable: true
  },
  {
    id: 'spris-juice',
    name: 'Layered Spris Juice',
    nameAm: 'የፍራፍሬ ስፕሪስ ጁስ',
    nameOm: 'Spris Juice',
    description: 'Beautiful tri-color layers of premium blended mango, papaya, guava, and avocado thick pulps.',
    descriptionAm: 'የአቮካዶ፣ የማንጎ እና የአናናስ ጁስ በአንድ መስታወት ላይ ተስማምቶ የሚቀርብ ድንቅ መጠጥ::',
    descriptionOm: 'Juice tri-color mango, avocado fi papaya makuu.',
    price: 120,
    category: 'cold-drinks',
    image: 'https://images.unsplash.com/photo-1536882240095-0379873feb4e?w=600&auto=format&fit=crop&q=80',
    isPopular: false,
    isAvailable: true
  },
  {
    id: 'spring-water',
    name: 'Highland Pure Spring Water',
    nameAm: 'የምንጭ ጥም ማስታገሻ ውሃ',
    nameOm: 'Bishaan Spring Water',
    description: 'Chilled or room-temperature premium glass-bottled organic highland volcanic spring mineral water.',
    descriptionAm: 'ታሽጎ የሚቀርብ ንፁህ የምንጭ ውሃ ለጤናዎ ተስማሚ::',
    descriptionOm: 'Bishaan qulqulluu qabbaneeffame.',
    price: 40,
    category: 'cold-drinks',
    image: 'https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=600&auto=format&fit=crop&q=80',
    isAvailable: true
  }
];

export const CATEGORIES: CategoryInfo[] = [
  {
    key: 'signature-goat',
    label: 'Signature Goat Specialties',
    labelAm: 'የፍየል ሥጋ ልዩ ምግቦች',
    labelOm: 'Signature Goat Specialties',
    description: 'Slaughtered fresh daily and prepared with Niter Kibbeh organic butter',
    descriptionAm: 'ከደጋማው አካባቢ በየቀኑ በጥንቃቄ ተመርጦ ትኩስ የሚታረድ ስጋ በንጥር ቅቤ የተዘጋጀ',
    descriptionOm: 'Foon re\'ee dhedharaa gaara irraa dhufe guyyaa guyyaan dhiyaatablee',
    count: 10
  },
  {
    key: 'traditional-foods',
    label: 'Traditional Favorites',
    labelAm: 'የሀገራችን ባህላዊ ምግቦች',
    labelOm: 'Traditional Favorites',
    description: 'Authentic Kitfo, Gored Gored, and Shiro cooked in boiling pots',
    descriptionAm: 'እውነተኛው ባህላዊ ክትፎ፣ ጎረድ ጎረድና በሸክላ የሚፈላ ሽሮ ተጋቢኖ',
    descriptionOm: 'Kitfo aadaa, gored gored fi kookii shiro clay pot keessatti bilcheeffame',
    count: 6
  },
  {
    key: 'breakfast',
    label: 'Breakfast Selection',
    labelAm: 'የጠዋት ባህላዊ ቁርስ',
    labelOm: 'Breakfast Selection',
    description: 'Sautéed Chechebsa, fluffy Kinche, and warm fava Foul',
    descriptionAm: 'ጣፋጭ ጨጨብሳ፣ ኪንጬ እና ከሎሚና እቁላል ጋር የሚቀርብ ልዩ ፉል',
    descriptionOm: 'Chechebsa damma wajjin, kinche fi foul speshall',
    count: 6
  },
  {
    key: 'soups-starters',
    label: 'Soups & Starters',
    labelAm: 'መረቆችና መቆያ ምግቦች',
    labelOm: 'Soups & Starters',
    description: 'Nutritional Ye-Feyel Marak soups and fresh crisp salads',
    descriptionAm: 'ጥንካሬ ሰጪ የፍየል እግርና የጎድን መቅኒ መረቅ እና ቲማቲም ሰላጣ',
    descriptionOm: 'Ye-Feyel Marak nutritious fi salad qaccinaawaa',
    count: 4
  },
  {
    key: 'hot-drinks',
    label: 'Hot Buna & Spiced Brews',
    labelAm: 'ሙቅ ጄበና ቡናና የቅመም ሻይ',
    labelOm: 'Hot Buna & Spiced Brews',
    description: 'Jebena Buna ceremony, foamy macchiatos, and organic spiced teas',
    descriptionAm: 'ጄበና ቡና ስነስርዓት ከፋንዲሻ ጋር፣ ምርጥ ማኪያቶና የቅመም ሻይ',
    descriptionOm: 'Sirna buna jebenan qophaaye fi shai qarafaa wajjin',
    count: 5
  },
  {
    key: 'cold-drinks',
    label: 'Cold Juices & Ambo Mineral',
    labelAm: 'ጁስ እና ቀዝቃዛ መጠጦች',
    labelOm: 'Cold Juices & Ambo Mineral',
    description: 'Thick layered avocado-mango smoothies and sparkling spring waters',
    descriptionAm: 'የፍራፍሬ ስፕሪስ ጁስ፣ ማንጎ ጁስ እና ቀዝቃዛ አምቦ ማዕድን ውሃ',
    descriptionOm: 'Sprite juice mango fi avocado makuu, bishaan ambo',
    count: 4
  }
];
